[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/renderIndex"
  status = 200

[[redirects]]
from = "/artistdash"
to = "/.netlify/functions/artistdash"
status = 200

[[redirects]]
from = "/artistpage"
to = "/.netlify/functions/artistpage"
status = 200

[[redirects]]
from = "/login"
to = "/.netlify/functions/login"
status = 200

[[redirects]]
from = "/signup"
to = "/.netlify/functions/signup"
status = 200

[functions]
  included_files = ["public/**"]